<?php

return [

    /*
    |--------------------------------------------------------------------
    | Daftar Kata Kasar
    |--------------------------------------------------------------------
    |
    | Kata-kata di bawah ini akan otomatis diblokir dari komentar
    | (lihat App\Rules\BebasKataKasar). Tulis dalam bentuk dasar/lowercase,
    | tidak perlu variasi leetspeak — normalisasi sudah menangani itu.
    |
    | Silakan tambah/kurangi sesuai kebutuhan tanpa perlu ubah kode.
    |
    */

    'daftar' => [
        // ===== Bahasa Indonesia - umum =====
        'anjing',
        'anjir',
        'anjrit',
        'anjay',
        'bangsat',
        'bajingan',
        'bajingan tengik',
        'babi',
        'babi ngepet',
        'goblok',
        'goblog',
        'tolol',
        'bego',
        'begok',
        'bodoh',
        'idiot',
        'dungu',
        'gblk',
        'kontol',
        'kntl',
        'kntol',
        'peler',
        'pler',
        'memek',
        'mmk',
        'meki',
        'ngentot',
        'ngentod',
        'entot',
        'ngewe',
        'pepek',
        'pukimak',
        'puki',
        'pukimai',
        'kampret',
        'kampang',
        'kampangan',
        'tai',
        'taik',
        'taek',
        'tae',
        'sinting',
        'gila',
        'edan',
        'setan',
        'iblis',
        'bangke',
        'bangkai',
        'jancok',
        'jancuk',
        'diancuk',
        'cok',
        'asu',
        'asw',
        'asuu',
        'brengsek',
        'brengsek lo',
        'sialan',
        'sial',
        'lonte',
        'pelacur',
        'perek',
        'jablay',
        'sundal',
        'bencong',
        'banci',
        'keparat',
        'laknat',
        'monyet',
        'kera',
        'kunyuk',
        'jembut',
        'jembud',
        'colmek',
        'coli',
        'ancrit',
        'ancur',
        'geblek',
        'gembel',
        'najis',
        'jijik',
        'sundala', 
        'kimak',
        'kimak jang',
        'kunti',
        'kuntilanak',
        'lu gila',
        'lu edan',
        'anak haram',
        'haram jadah',
        'tolol lu',
        'goblok lu',

        'anj',
        'anjg',
        'anjrot',
        'knt',
        'k0ntol',
        'kont0l',
        'mmek',
        'mem3k',
        'ngntd',
        'ngnt0t',
        'tll',
        't0lol',
        'gblk',
        'g0blok',
        'bgsd',
        'bgst',
        'as*',
        'a5u',

        // ===== English - profanity =====
        'fuck',
        'fucker',
        'fucking',
        'motherfucker',
        'fck',
        'fuk',
        'fuq',
        'shit',
        'bullshit',
        'shitty',
        'bitch',
        'bitches',
        'son of a bitch',
        'asshole',
        'ass',
        'jackass',
        'bastard',
        'damn',
        'goddamn',
        'dick',
        'dickhead',
        'cock',
        'pussy',
        'cunt',
        'slut',
        'whore',
        'retard',
        'retarded',
        'moron',
        'idiot',
        'stupid',
        'douche',
        'douchebag',
        'crap',
        'piss',
        'pissed off',
        'nigger',
        'nigga', 
        'faggot',
        'fag',

        // ===== Variasi English disamarkan =====
        'f*ck',
        'f**k',
        'sh*t',
        'b*tch',
        'a**hole',
        'fu*k',
        'fck',
        'fuxk',
    ],

];